import { Serie } from "./serie.js";
export const series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://tse1.mm.bing.net/th/id/OIP.pwxl5Ab8HfWw6XX8WHOyNwHaFB?pid=Api&P=0&h=180"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://tse3.mm.bing.net/th/id/OIP.jxVEVcJbVqdC4mxBthQjnwHaLH?pid=Api&P=0&h=180"),
    new Serie(3, "Game of Thrones", "HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://tse4.mm.bing.net/th/id/OIP.NoQ9Hg-KnJuQOtJW_tbezgHaE8?pid=Api&P=0&h=180"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://tse2.mm.bing.net/th/id/OIP.8ez6TPwPpZEtd__pxuWkOQHaFj?pid=Api&P=0&h=180"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws", "https://tse1.mm.bing.net/th/id/OIP._9zaPhgjngaI_xc8JmbDFQHaEK?pid=Api&P=0&h=180"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://tse4.mm.bing.net/th/id/OIP.IiZFeM2NM0zpvJixGEZCFAHaEK?pid=Api&P=0&h=180")
];
